### ISSUE TITLE
WSL接続の際の注意点を追加する

### ISSUE THREAD

**Issue by 661nos** [utphys-comp/utphys-comp.github.io#3]
当方WSL2によってaiサーバーに接続しました。その際、`ssh-add`コマンドが機能せず、調べたところ、どうやらwindowsでは初めに`` eval `ssh-agent` ``コマンドを打つ必要があるようです。詳細は[この記事](https://qiita.com/sshojiro/items/60982f06c1a0ba88c160)に書いてあります。この通りにするとうまくいったので、接続に関しては問題ないです。しかし、資料にはWSL時にもceenvと同じようにすればできると書いてあり、混乱の原因にもなると思うので、この部分に上記を追加してはどうでしょうか。

**Comment by wistaria** [comment]
@661nos ご指摘ありがとうございます。修正しました。
